const SPINBOX_STATE = {
  INITIAL_ID: 0,
  INITIAL_DELAY_TIME: 1000,
  INITIAL_INPUT_VALUE: 0,
  INITIAL_TIMEOUT_ID: 0,
  LEFT_BUTTON: 0,
  MINIMUM_DELAY_TIME: 10,
  DELAYTIME_DECREASE_RATE: 1.125,
};

export default SPINBOX_STATE;
